runtime: go111

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: auto

# nobuild_files is a regexp that identifies which files to not build.  It
# is useful for embedding static assets like code snippets and preventing
# them from producing build errors for your project.

nobuild_files: content/|pingserver/
